import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// European first names
const firstNames = [
  "Alexander",
  "Anastasia",
  "Andreas",
  "Anna",
  "Anton",
  "Barbara",
  "Boris",
  "Carlos",
  "Catherine",
  "Christian",
  "Daniel",
  "Dimitri",
  "Elena",
  "Emma",
  "Erik",
  "Eva",
  "Felix",
  "Francesco",
  "Gabriel",
  "Giovanni",
  "Hans",
  "Helena",
  "Henrik",
  "Igor",
  "Ivan",
  "Jakob",
  "Jan",
  "Johann",
  "Julia",
  "Karl",
  "Katerina",
  "Klaus",
  "Lars",
  "Leon",
  "Lucia",
  "Ludwig",
  "Lukas",
  "Marco",
  "Maria",
  "Martin",
  "Matteo",
  "Max",
  "Michael",
  "Mikhail",
  "Natalia",
  "Nikolai",
  "Olga",
  "Oscar",
  "Pablo",
  "Paolo",
  "Peter",
  "Pierre",
  "Rafael",
  "Robert",
  "Sebastian",
  "Sergei",
  "Sofia",
  "Stefan",
  "Svetlana",
  "Thomas",
  "Victor",
  "Viktor",
  "Vladimir",
  "Wolfgang",
  "Adrian",
  "Agnes",
  "Alina",
  "Andrei",
  "Angelina",
  "Anja",
  "Antoine",
  "Beatrice",
  "Brigitte",
  "Bruno",
  "Carla",
  "Charlotte",
  "Clara",
  "Diego",
  "Dominique",
  "Elise",
  "Emilia",
  "Florian",
  "Francesca",
  "Franz",
  "George",
  "Gustav",
  "Ingrid",
  "Isabella",
  "Jacques",
  "Jean",
  "Johanna",
  "Jose",
  "Julien",
  "Katrin",
  "Kristina",
  "Lena",
  "Leonardo",
  "Louisa",
  "Manuel",
  "Marcel",
  "Margot",
  "Marie",
  "Marta",
  "Matthias",
  "Maximilian",
  "Miguel",
  "Nadia",
  "Nicolas",
  "Nina",
  "Olivier",
  "Patricia",
  "Paul",
  "Petra",
  "Philippe",
  "Raphael",
  "Ricardo",
  "Rosa",
  "Sabrina",
  "Samuel",
  "Sandra",
  "Simon",
  "Sophia",
  "Stephan",
  "Tatiana",
  "Teresa",
  "Valentin",
  "Veronica",
  "Vincent",
  "Yvonne",
];

// European last names
const lastNames = [
  "Anderson",
  "Becker",
  "Bernard",
  "Blanc",
  "Brown",
  "Costa",
  "Dubois",
  "Ferrari",
  "Fischer",
  "Garcia",
  "Gonzalez",
  "Hansen",
  "Hoffman",
  "Ivanov",
  "Jensen",
  "Johansson",
  "Johnson",
  "Klein",
  "Koch",
  "Kowalski",
  "Larsen",
  "Lopez",
  "Martinez",
  "Meyer",
  "Miller",
  "Moller",
  "Moreau",
  "Muller",
  "Nielsen",
  "Novak",
  "Olsen",
  "Petrov",
  "Popov",
  "Richard",
  "Rodriguez",
  "Romano",
  "Rossi",
  "Russo",
  "Schmidt",
  "Schneider",
  "Silva",
  "Smirnov",
  "Smith",
  "Sokolov",
  "Sorensen",
  "Thomas",
  "Wagner",
  "Weber",
  "Williams",
  "Wilson",
  "Andersen",
  "Bauer",
  "Berger",
  "Bergmann",
  "Brandt",
  "Braun",
  "Christiansen",
  "Colombo",
  "Dahl",
  "Esposito",
  "Fernandez",
  "Frank",
  "Friedrich",
  "Gallo",
  "Giordano",
  "Greco",
  "Gruber",
  "Hartmann",
  "Hoffmann",
  "Huber",
  "Jansen",
  "Jorgensen",
  "Jung",
  "Kaiser",
  "Keller",
  "Konig",
  "Kovacs",
  "Kraus",
  "Krawczyk",
  "Lang",
  "Lange",
  "Lehmann",
  "Lombardi",
  "Marino",
  "Martin",
  "Mayer",
  "Meijer",
  "Molina",
  "Nagy",
  "Navarro",
  "Neumann",
  "Otto",
  "Peeters",
  "Perez",
  "Pohl",
  "Ricci",
  "Richter",
  "Roth",
  "Ruiz",
  "Sanchez",
  "Santos",
  "Schmid",
  "Schulz",
  "Schwarz",
  "Sergeyev",
  "Simon",
  "Sorensen",
  "Steiner",
  "Szabo",
  "Varga",
  "Voigt",
  "Volkov",
  "Walter",
  "Werner",
  "Wolf",
  "Zimmermann",
];

// Interests
const interests = [
  "music",
  "art",
  "nature",
  "sports",
  "travel",
  "food",
  "technology",
  "gaming",
  "outdoors",
  "hiking",
  "reading",
  "photography",
  "cinema",
  "theater",
  "dancing",
  "cooking",
  "fitness",
  "yoga",
  "meditation",
  "cycling",
  "swimming",
  "skiing",
  "surfing",
  "climbing",
  "camping",
  "fishing",
  "gardening",
  "painting",
  "drawing",
  "sculpture",
  "poetry",
  "writing",
  "blogging",
  "vlogging",
  "fashion",
  "design",
  "architecture",
  "history",
  "science",
  "astronomy",
  "physics",
  "chemistry",
  "biology",
  "psychology",
  "philosophy",
  "languages",
  "culture",
  "volunteering",
  "sustainability",
  "environment",
  "running",
  "tennis",
  "football",
  "basketball",
  "volleyball",
  "chess",
  "boardgames",
  "knitting",
  "crafts",
  "wine",
  "coffee",
  "tea",
  "baking",
  "diy",
  "electronics",
  "robotics",
  "anime",
  "manga",
  "comics",
  "scifi",
  "fantasy",
  "horror",
  "mystery",
  "jazz",
  "rock",
  "classical",
  "electronic",
  "pop",
  "indie",
  "metal",
];

// Generate users
const users = [];
console.log("Generating 10,000 users...");

for (let i = 1; i <= 10000; i++) {
  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];

  // Generate 5 unique random interests
  const userInterests = [];
  const interestSet = new Set();
  while (interestSet.size < 5) {
    interestSet.add(interests[Math.floor(Math.random() * interests.length)]);
  }
  userInterests.push(...Array.from(interestSet));

  // Generate random coordinates within Europe
  // Latitude: 36°N (Southern Spain/Greece) to 71°N (Northern Norway)
  // Longitude: -10°W (Western Ireland) to 40°E (Eastern Europe)
  const lat = 36 + Math.random() * 35;
  const lon = -10 + Math.random() * 50;

  users.push({
    id: i,
    name: `${firstName} ${lastName}`,
    interests: userInterests,
    position: [parseFloat(lat.toFixed(4)), parseFloat(lon.toFixed(4))],
  });

  // Progress indicator
  if (i % 1000 === 0) {
    console.log(`Generated ${i} users...`);
  }
}

// Create data directory if it doesn't exist
const dataDir = path.join(__dirname, "src", "data");
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

// Write to file
const filePath = path.join(dataDir, "users.json");
fs.writeFileSync(filePath, JSON.stringify(users, null, 2));

console.log(`✓ Successfully created ${filePath} with 10,000 users!`);
console.log(
  `File size: ${(fs.statSync(filePath).size / 1024 / 1024).toFixed(2)} MB`
);
